# Generated by Django 4.2 on 2023-05-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='rating',
        ),
    ]
