# Generated by Django 4.2 on 2023-05-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_remove_blog_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='release_date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
