# Generated by Django 4.2.1 on 2023-05-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='images/Blog_pic.png', upload_to='images/'),
        ),
    ]
